# ASP.NET Core
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "*****************"
      $chrome = (google-chrome --version)
      Write-Host "$chrome"
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: Default 

variables:
  buildConfiguration: 'Release'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
